// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmkvwcnfeajaactmwsio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpta3Z3Y25mZWFqYWFjdG13c2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzOTE1MjYsImV4cCI6MjA3OTk2NzUyNn0.F7tejMETFJxkcLxmMDcwII4McV-VGTIBiYr1pQe6s1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});